### ISSUE TITLE
Update Project Reference from 3U to 4U

### ISSUE THREAD

**Issue by kamegami13** [kamegami13/MonsterHunter4UDatabase#2]
Change all project references of 3U to 4U.

**Comment by Armi23** [comment]
Are we talking renaming the databases as well? All path names and *.db files included?

**Comment by kamegami13** [comment]
Yes. I already started and am almost done. I should have assigned myself first.
.

**Comment by Armi23** [comment]
I was working on it as well and I think I'm done (builds successfully and runs without any new errors), but unfortunately I don't know how to make pull requests (I'll look into that now anyways). We'll just wait for you changes, but I noticed two things: 

1. There's a SQL database error (present in the clean repo) that we should get resolved about the database file not being found. I assume a simple check for its existence should work, rather than creating a try catch and relying on that. 
2. If we're changing package names, maybe we should change the com.daviancorp.android package as well? I assume the "daviancorp" is from an old version of the package and if we want to change it eventually we should do it sooner rather than later when we might have more people on the project.

**Comment by kamegami13** [comment]
I got it done and merged it.

1. We should make that a separate pull. By all means fix any and all database issues you find.
2. It is possible we should. The original creators are following the project. This needs to be discussed, I will go ahead and make a topic.
